version: '3.7'

services:

  airflow:
    build: ./dockerfiles
    restart: always
    environment:
      - INSTALL_MYSQL=y
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW_DATABASE_URL=postgresql://airflow:airflow@postgres/airflow
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ../scripts:/usr/local/airflow/includes
      # - ../dbt_:/usr/local/airflow/dbt_
      - ../data:/usr/local/airflow/data
      - ../airflow_/logs:/opt/airflow/logs
      - ../airflow_/plugins:/opt/airflow/plugins
    ports:
      - "8083:8080"
    command: webserver

  
networks: 
  default: 
    external: 
      name: network1